site_name: Moose Capacity Model
theme: readthedocs
site_url: "https://capacity.moosejudge.com"
repo_url: "https://gitlab.com/TheChuckMo/moosecap"
site_author: "Chuck Mo <chuck@moosejudge.com>"

prebuild_index: true

markdown_extensions:
  - smarty
  - toc:
      permalink: True
  - sane_lists
